#pragma config(Sensor, S1,     Magazin,        sensorEV3_Color)
#pragma config(Motor,  motorA,          MotorLinks,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          MotorRechts,   tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          Nachladen,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          DrehTurm,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void Init(){
	eraseDisplay();
	sensorReset(Magazin);
	resetMotorEncoder(motorA);
	resetMotorEncoder(motorB);
	resetMotorEncoder(motorC);
	resetMotorEncoder(motorD);}


int ladenExecuted = 1;
void Laden() {
    if (ladenExecuted == 1) {
        setMotorSyncEncoder(motorA, motorB, 0, 3640, 100);
        delay(4000);
        setMotorTarget(motorC, 180, 15);
        waitUntilMotorStop(motorC);
        delay(1000);
        setMotorTarget(motorC, 0, 15);
        waitUntilMotorStop(motorC);
        ladenExecuted = ladenExecuted - 1;
    if (getButtonPress(buttonLeft)){
				setMotorSpeed(motorD, 10);}

		else if (getButtonPress(buttonRight)){
				setMotorSpeed(motorD, -10);}}
}




task main()
{
Init();
int Patronen;

while (true){
getColorReflected(S1);
Patronen = getColorReflected(S1);

	if (Patronen >= 7){
			displayBigTextLine(3, "Munition Voll!");
			delay(200);
			Laden();

	if (getButtonPress(buttonLeft)){
			setMotorSpeed(motorD, 10);}

	else if (getButtonPress(buttonRight)){
			setMotorSpeed(motorD, -10);}

	else {
			setMotorSpeed(motorD, 0);}

	if (getButtonPress(buttonEnter)){
			ladenExecuted = ladenExecuted + 1;}

	while (getButtonPress(buttonEnter)){
			setMotorSyncEncoder(motorA, motorB, 0, 5040, 100);
	  	delay(5400);
			Laden();}
	}


	else if (Patronen <=6){
		displayBigTextLine(3, "Munition Leer!");

		if (getButtonPress(buttonLeft)){
		setMotorSpeed(motorD, 10);}

		else if (getButtonPress(buttonRight)){
			setMotorSpeed(motorD, -10);}

		else {
		setMotorSpeed(motorD, 0);}
	}
}
}
